# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Davut Ucar
title: Software Engineer
email: davutucar@gmail.com
#website: www.github.com/dauut

# Social links
#twitter_username: dauutt
github_username:  dauut
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: davutucar
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a self-motivated, result-oriented, and 2.5+ years experienced software engineer. I graduated from [UNR](https://www.unr.edu/) with a Master's degree in May 2020. I worked on "Stream file throughput optimization" with supercomputers. Also, I am interested in state-of-the-art technologies and have a passion for problem-solving.

# I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  [Medium](https://medium.com/@davut) posts:
   - [Hadoop and HBase setup on Ubuntu (*Turkish*)](https://medium.com/@davut/ubuntu-%C3%BCzerine-da%C4%9F%C4%B1t%C4%B1k-multi-node-hadoop-2-7-2-ve-hbase-1-2-0-kurulumu-56190d81baa5)
   - [Big Data and Hadoop (*Turkish*)](https://medium.com/bili%C5%9Fim-hareketi/b%C3%BCy%C3%BCk-veri-ve-hadoop-92a19f0b7efd)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
